# here you can call the scripts

type: script
scripts:
  # this sets up the proper policy & signing files for signed images to work
  - signing.sh
  #- pre-install.sh
  #- dotfiles.sh
  - post-install.sh
