# you can enable and disable systemd services here

type: systemd
system:
  enabled:
     - display-manager.service
     - sddm.service
  #  - power-profiles-daemon
  disabled:
     #- lightdm 
     #- gdm 
     #- lxdm 
     #- lxdm-gtk3
   # - rpm-ostree-countme.timer
