# you can enable and disable systemd services here

type: systemd
system:
  enabled:
     #- sddm
     - display-manager
     #- power-profiles-daemon
  disabled:
     #- lightdm 
     #- gdm 
     #- lxdm 
     #- lxdm-gtk3
   # - rpm-ostree-countme.timer
