# image will be published to ghcr.io/<user>/<name>
name: viper-nvidia
# description will be included in the image's metadata
description: This is Viper OS image for NVIDIA users.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module

modules:
  - from-file: common.yml
#  - from-file: module_config/nvidia.yml

